# Generated by Django 4.1 on 2022-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwixs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(default=' ', max_length=2),
        ),
        migrations.AddField(
            model_name='business',
            name='zipcode',
            field=models.CharField(default=' ', max_length=5),
        ),
    ]
