# Generated by Django 4.1 on 2022-09-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwixs', '0002_business_city_business_state_business_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='zipcode',
            field=models.CharField(default=' ', max_length=6),
        ),
    ]
