# Generated by Django 4.1 on 2022-09-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwixs', '0003_business_about_alter_business_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='about',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
