# Generated by Django 4.1.1 on 2022-09-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwixs', '0005_business_image_url_alter_business_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about_image',
            field=models.CharField(default='About Image', max_length=255),
        ),
    ]
