# Generated by Django 4.1.1 on 2022-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwixs', '0006_business_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='zipcode',
            field=models.CharField(default=' ', max_length=7),
        ),
    ]
